### ISSUE TITLE
wapm: error while loading shared libraries

### ISSUE THREAD

**Issue by bimohxh** [wasmerio/wapm-cli#59]
I just fllow the installing step

```bash
curl https://get.wasmer.io -sSfL | sh
```

this work will and I can get `wasmer` command, but when I run `wapm` I got the error

> wapm: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by ctaggart** [comment]
I get the same error. Ubuntu 16.04 Xenial comes with openssl 1.0, not 1.1.

```
cameron@USENTAGGACL1C:/mnt/c/Users/taggac/tmp$ wapm install cowsay lolcat
wapm: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
cameron@USENTAGGACL1C:/mnt/c/Users/taggac/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

https://launchpad.net/ubuntu/xenial/+source/openssl

I looks like Bionic has openssl 1.1:
https://launchpad.net/ubuntu/bionic/+source/openssl

**Comment by MarkMcCaskey** [comment]
Upgrading to Ubuntu 18 fixed this on my home computer.  I don't know if there's a better solution than that.

I believe the common wisdom is to dynamically link security critical libraries like this so that users can upgrade/patch vulnerabilities on their own without waiting for a new release.  It's unfortunate that it doesn't work at all on libssl1.0 though.  I don't have context on the differences right now, but this is something we can look into if it's going to impact a large number of users

**Comment by MarkMcCaskey** [comment]
according to https://wiki.ubuntu.com/Releases it will be supported for 3-6 more years, so that's not great.  And I'm sure there are people who aren't able to upgrade 🤔

**Comment by MarkMcCaskey** [comment]
This seems to be coming from `reqwest` https://crates.io/crates/reqwest : 
>  On Linux, it will use OpenSSL 1.1.

**Comment by MarkMcCaskey** [comment]
It should hopefully just work on the next release.  I'll test it when I get home tonight
